<a href="https://colab.research.google.com/github/viett887g/numpy1/blob/main/numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import math
import random as rd

In [ ]:
Bài 1: Xét không gian R3

, một điểm A trong không gian này có tọa độ là (5, 7, 14). Hãy khởi tạo

giá trị của điểm A nêu trên bằng Numpy.

In [13]:
a1 = np.array([[5],[7],[14]])

In [ ]:
Bài 2: Mở rộng không gian lên R15, điểm A trong không gian này có tọa độ là (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15). Hãy khởi tạo điểm A trong không gian 15 chiều này bằng Numpy.

In [12]:
a2 = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10],[11],[12],[13],[14],[15]])

print(a2)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]]


In [ ]:
Hãy viết chương trình sinh ngẫu nhiên một vector trong không gian Rn với n là số nguyên dương
được nhập vào từ bàn phím. Yêu cầu: sử dụng Numpy.

In [14]:
n = int(input('Nhập số chiều trong không gian của vector A: '))
print('\n')

a3 = []

for i in range(n):
    print('Nhập tọa độ của A('+ str(i+1) +') tương ứng với số chiều trong không gian: ',end="")
    i = [int(input())]
    a3.append(i)
print(a3)
vecA = np.array(a3)    
print("\n Vector A bạn vừa tạo là: \n", vecA)

Nhập số chiều trong không gian của vector A: 5


Nhập tọa độ của A(1) tương ứng với số chiều trong không gian: 12
Nhập tọa độ của A(2) tương ứng với số chiều trong không gian: 5
Nhập tọa độ của A(3) tương ứng với số chiều trong không gian: 2
Nhập tọa độ của A(4) tương ứng với số chiều trong không gian: 4
Nhập tọa độ của A(5) tương ứng với số chiều trong không gian: 2
[[5], [6], [4], [12], [5], [2], [4], [2]]

 Vector A bạn vừa tạo là: 
 [[ 5]
 [ 6]
 [ 4]
 [12]
 [ 5]
 [ 2]
 [ 4]
 [ 2]]


In [ ]:
Trong không gian R3

xét vector OA⃗⃗⃗⃗⃗

In [ ]:
Hãy viết chương trình tính chiều dài của vector OA⃗⃗⃗⃗⃗ , biết công thức tổng quát để tính chiều dài
vector OA⃗⃗⃗⃗⃗ trong không gian Rn
là:

In [5]:
vecA = np.array([[7],[-5],[8]])
print("Vector A là: ", vecA)
n = 0

for i in vecA:
    n += i**2
    
vecOA = math.sqrt(n)
print("Chiều dài vector OA (với O là gốc tạo độ) là: ", vecOA)

Vector A là:  [[ 7]
 [-5]
 [ 8]]
Chiều dài vector OA (với O là gốc tạo độ) là:  11.74734012447073


In [ ]:
Bài 5: Trong không gian Rn

, hãy sinh ngẫu nhiên 2 điểm A và B. Xác định vector AB⃗⃗⃗⃗⃗ và tính

chiều dài của vector này ‖AB⃗⃗⃗⃗⃗ ‖. Lưu ý: sử dụng Numpy.

In [6]:
n = int(input("Nhập số chiều trong không gian: "))
vecA = []
vecB = []

for i in range(n):
    i = [rd.random()]
    vecA.append(i)
    i = [rd.random()]
    vecB.append(i)

vecA = np.array(vecA)
print("Vector A được khởi tạo là: ", vecA)
vecB = np.array(vecB)
print("Vector B được khởi tạo là: ", vecB)
vecAB = vecA + vecB

n = 0
for i in vecAB:
    n += i**2

vecAB = math.sqrt(n)
print("Chiều dài của vector AB là: ", vecAB)

Nhập số chiều trong không gian: 4
Vector A được khởi tạo là:  [[0.18753024]
 [0.48348186]
 [0.55405206]
 [0.15468025]]
Vector B được khởi tạo là:  [[0.8708678 ]
 [0.1039738 ]
 [0.15065346]
 [0.3595246 ]]
Chiều dài của vector AB là:  1.492088151134861


In [ ]:
Bài 6: Tích vô hướng của 2 vector a & b⃗ (dot product hoặc inner product hoặc scalar product) được tính theo công thức tổng quát là:

a ∙ b⃗ = a1b1 + a2b2 + ⋯ + anbn

Trong không gian Rn

, hãy sinh ngẫu nhiên 2 vector a & b⃗ và tính tích vô hướng của 2 vector này. Lưu ý: sử dụng numpy để tính tích vô hướng và số nguyên dương n được nhập vào từ bàn phím. Gợi ý: sử dụng hàm numpy.inner()

In [7]:
n = int(input("Nhập số chiều trong không gian: "))
vecA = []
vecB = []

for i in range(n):
    i = [rd.random()]
    vecA.append(i)
    i = [rd.random()]
    vecB.append(i)
    

vecA = np.array(vecA)
print("Vector A được khởi tạo là: ", vecA)
vecB = np.array(vecB)
print("Vector B được khởi tạo là: ", vecB)
print("Tích vô hướng của vector AB là: ",np.inner(np.array(vecA), np.array(vecB)))

Nhập số chiều trong không gian: 5
Vector A được khởi tạo là:  [[0.5616521 ]
 [0.21026447]
 [0.34075823]
 [0.31157355]
 [0.35597872]]
Vector B được khởi tạo là:  [[0.41074821]
 [0.46967139]
 [0.99019261]
 [0.18145914]
 [0.52157985]]
Tích vô hướng của vector AB là:  [[0.23069759 0.26379192 0.55614376 0.10191691 0.29294642]
 [0.08636575 0.0987552  0.20820232 0.03815441 0.10966971]
 [0.13996583 0.16004439 0.33741628 0.0618337  0.17773263]
 [0.12797828 0.14633718 0.30851783 0.05653787 0.16251049]
 [0.14621762 0.16719302 0.3524875  0.06459559 0.18567133]]


In [ ]:
Bài 7: Tích hữu hướng (cross product) của 2 vector a & b⃗ được tính theo công thức tổng quát là:

a × b⃗ = ‖a ‖‖b⃗ ‖ sin(θ)

Trong không gian Rn

, hãy sinh ngẫu nhiên 2 vector a & b⃗ và tính tích hữu hướng của 2 vector này. Lưu ý: sử dụng numpy để tính tích vô hướng và số nguyên dương n được nhập vào từ bàn phím. Gợi ý: sử dụng hàm numpy.cross()

In [8]:
n = int(input("Nhập số chiều trong không gian: "))
vecA = []
vecB = []

for i in range(n):
    i = [rd.random(),rd.random(),rd.random()]
    vecA.append(i)
    i = [rd.random(),rd.random(),rd.random()]
    vecB.append(i)
    
vecA = np.array(vecA)
print("Vector A được khởi tạo là: ", vecA)
vecB = np.array(vecB)
print("Vector B được khởi tạo là: ", vecB)
z = np.cross(vecA, vecB)
print(z)

Nhập số chiều trong không gian: 5
Vector A được khởi tạo là:  [[0.59035888 0.10232238 0.59098417]
 [0.58414987 0.71042774 0.80670278]
 [0.41374254 0.52370945 0.84288886]
 [0.95218486 0.0439107  0.77671321]
 [0.181188   0.79927363 0.58940377]]
Vector B được khởi tạo là:  [[0.15085047 0.22086619 0.1836506 ]
 [0.87116169 0.41585201 0.59098699]
 [0.26272399 0.90800064 0.96290536]
 [0.74652991 0.78949058 0.44832616]
 [0.6033746  0.78180238 0.34501004]]
[[-0.11173685 -0.01926952  0.11495494]
 [ 0.08438458  0.35754358 -0.37597753]
 [-0.26106099 -0.17694778  0.23808745]
 [-0.59352144  0.15295027  0.71896032]
 [-0.18503984  0.29311959 -0.3406082 ]]


In [ ]:
Bài 8 - Phép chuyển vị (transpose): trong numpy, một vector a khi thực hiện chuyển vị sẽ được thực hiện thông qua thao tác a.T Hãy viết chương trình sinh ngẫu nhiên một vector a trong không gian Rn

, số nguyên dương n được nhập vào từ bàn phím. Xuất ra màn hình giá của vector a và chuyển vị của vector a .

In [9]:
n = int(input("Nhập số chiều trong không gian: "))
vecA = []

for i in range(n):
    i = [rd.randint(1,10),rd.randint(1,10),rd.randint(1,10)]
    vecA.append(i)
    
vecA = np.array(vecA)
print("Vector A được khởi tạo là: ", vecA)
print("Ma trận chuyển vị của vector A là: ", np.transpose(vecA,(1,0)))

Nhập số chiều trong không gian: 5
Vector A được khởi tạo là:  [[4 8 6]
 [6 6 5]
 [6 1 2]
 [8 4 2]
 [8 7 6]]
Ma trận chuyển vị của vector A là:  [[4 6 6 8 8]
 [8 6 1 4 7]
 [6 5 2 2 6]]


In [ ]:
Bài 9 - Kết hợp cấu trúc list với Numpy: Xét 2 cấu trúc list dưới đây:

a = [1, 2, 3, 4, 5]
b = [[1], [2], [3], [4], [5]] Hãy:  Xuất a và b ra màn hình  Tạo vector tương ứng từ a và b, xuất kết quả ra màn hình  Thực hiện phép chuyển vị đối với 2 vector ở trên và xuất kết quả ra màn hình.

In [10]:
a = [1,2,3,4,5]
b = [[1],[2],[3],[4],[5]]
print(a)
print(b)

a = np.array(a)
b = np.array(b)
print(a)
print(b)

a = np.transpose(a)
b = np.transpose(b)
print(a)
print(b)

[1, 2, 3, 4, 5]
[[1], [2], [3], [4], [5]]
[1 2 3 4 5]
[[1]
 [2]
 [3]
 [4]
 [5]]
[1 2 3 4 5]
[[1 2 3 4 5]]


In [ ]:
Bài 10: Trong không gian Rn

, hãy sinh ngẫu nhiên vector a và b⃗ , n là số nguyên dương nhập vào

từ bàn phím. Hãy:  Thực hiện phép nhân: ma với m là số bất kỳ, xuất kết quả ra màn hình  Thực hiện phép cộng 2 vector: a + b⃗ và xuất kết quả ra màn hình.

In [11]:
n = int(input("Nhập số chiều trong không gian: "))
vecA = []
vecB = []

for i in range(n):
    i = [rd.randint(1,100),rd.randint(1,100),rd.randint(1,100)]
    vecA.append(i)
    i = [rd.randint(1,100),rd.randint(1,100),rd.randint(1,100)]
    vecB.append(i)
    
vecA = np.array(vecA)
print("Vector A được khởi tạo là: ", vecA)
vecB = np.array(vecB)
print("Vector B được khởi tạo là: ", vecB)

print("vector A * m = ", vecA * rd.randint(1,10))
print("vector A + vector B = ", vecA + vecB)

Nhập số chiều trong không gian: 5
Vector A được khởi tạo là:  [[32 72  9]
 [22 96 96]
 [87 47 79]
 [76 42 93]
 [ 5 19 43]]
Vector B được khởi tạo là:  [[42 77 65]
 [30 94 75]
 [46 89  2]
 [30 66 53]
 [18 76 92]]
vector A * m =  [[ 96 216  27]
 [ 66 288 288]
 [261 141 237]
 [228 126 279]
 [ 15  57 129]]
vector A + vector B =  [[ 74 149  74]
 [ 52 190 171]
 [133 136  81]
 [106 108 146]
 [ 23  95 135]]
